Added Norwegian-Bokmål translation
m2049r/xmrwallet pull request #238
Opened 2018-04-20 19:04 UTC by Codivorous

2018-04-21 08:34 UTC, m2049r commented
Thank you!
Strings marked with ```translatable="false"``` should not be translated (i.e. should be left out of the translated file). @erciccione maybe you can add this to the taiga instructions.
Please rebase to current master as we have new texts in ```strings.xml``` and a section in ```help.xml```.

2018-04-21 09:14 UTC, Codivorous commented
Oh, okay! I thought they should be left in, but not translated. I'll rebase and push :)

2018-04-21 09:26 UTC, erciccione commented
@m2049r actually is already in the instructions, maybe is not clear enough, will check it and rewrite if necessary

2018-04-21 09:38 UTC, Codivorous commented
I believe I got everything :) Also, the language codes for Norwegian are confusing. Some projects use "nb-no" and "nn-no" for bokmål and nynorsk, some only have one (aka. "no") and some have "nb" and "nn". I don't know which one to use, so I just used nb.

2018-04-21 10:00 UTC, erciccione approved these changes
Looks goo to me, thanks @Codivorous Can you squahs those commits in just one?

2018-04-21 10:01 UTC, Codivorous commented
I don't have access to a Git client at the moment unfortunately, as I've just done this through the web interface. Don't know how I would do that, sorry :p

2018-04-21 10:03 UTC, Codivorous commented
I'm fine with you forking my thing, squashing it and then pushing it btw. I don't care about the credits :p

2018-04-21 10:06 UTC, erciccione commented
Don't worry it's not a big deal, maybe @m2049r can just use the "squash and merge" option here on github

2018-04-21 11:02 UTC, Codivorous commented
Oh, okay! ^_^

2018-04-21 11:42 UTC, erciccione commented
Please revert the last commit (a175fdb) those strings don't have to be translated by they must be there

2018-04-21 13:33 UTC, Codivorous commented
>Strings marked with translatable="false" should not be translated (i.e. should be left out of the translated file).

2018-04-21 13:42 UTC, erciccione commented
@Codivorous I'm definitely still feeling the friday night, ignore my previous comment.
@m2049r now i got it. updating the instructions

2018-04-21 18:47 UTC, m2049r commented on app/src/main/res/values-nb/strings.xml
> +    <string name="info_send_xmrto_success_status_label">Status:</string>
pls delete this (info_send_xmrto_success_status_label) - does not exist in original

2018-04-21 18:49 UTC, m2049r requested changes

2018-04-21 18:49 UTC, m2049r commented on app/src/main/res/values-nb/strings.xml
> +    <string name="info_send_xmrto_success_status_label">Status:</string>
please delete this (info_send_xmrto_success_status_label) - does not exist in original

2018-04-21 18:49 UTC, m2049r commented on app/src/main/res/values-nb/help.xml
> +        Hvis passordet vist her er 52 alfanunmeriske karakterer i grupper av 4 - gratulerer!
please remove extra spaces at end of line.

2018-04-22 09:11 UTC, Codivorous commented
I'm sorry for making so many commits :p

2018-04-22 09:57 UTC, m2049r requested changes

2018-04-22 09:57 UTC, m2049r commented on app/src/main/res/values-nb/strings.xml
> +    <string name="info_send_xmrto_success_status">%1$s er %1$s (#%1$d)</string>
uhm... one last thing :) remove the string ```info_send_xmrto_success_status```

2018-04-22 10:15 UTC, Codivorous commented
Should I just create a new pull request so you only get one commit? Because this is getting ridiculous, so unless you have some magical un-commiting tool then that's probably for the best :p

2018-04-22 13:36 UTC, m2049r approved these changes

2018-04-22 13:37 UTC, merged

2018-04-22 13:37 UTC, m2049r commented
yay!

2018-04-22 13:39 UTC, m2049r commented
when merging i have to option to tell github to squash commits before merging

2018-04-22 13:58 UTC, Codivorous commented
Great! Thank you for all your assistance!