Romanian translation - strings.xml
m2049r/xmrwallet pull request #241
Opened 2018-04-21 03:26 UTC by AlexUnderHood

2018-04-21 08:44 UTC, m2049r commented
please rebase to current master - we have some new strings (in ```strings.xml```) and text in ```help.xml```. sorry about that.

2018-04-21 18:50 UTC, m2049r requested changes

2018-04-21 18:50 UTC, m2049r commented on app/src/main/res/values-ro/strings.xml
> +    <string name="send_qr_address_invalid">Cod QR de plată invalid/string>
```/string>``` => ```</string>```

2018-04-21 18:50 UTC, m2049r commented on app/src/main/res/values-ro/strings.xml
> +    <string-array name="currency" translatable="false">
please remove all strings with ```translatable="false"```

2018-04-30 09:54 UTC, erciccione commented
Pinged @AlexUnderHood on reddit. Pinging also here

2018-05-10 15:20 UTC, m2049r commented
@AlexUnderHood following translations are missing

- menu_changepw
- info_crazypass_enabled
- changepw_progress
- changepw_failed
- changepw_success
- prompt_changepw
- prompt_changepwB
- prompt_fingerprint_auth
- bad_fingerprint
- generate_fingerprint_hint
- generate_fingerprint_warn
- generate_bad_passwordB
- generate_empty_passwordB
- generate_crazypass_label

2018-05-14 21:36 UTC, erciccione commented
still no answer from @AlexUnderHood . @m2049r Could you fix and recover this as we talked on IRC?

2018-05-27 09:54 UTC, erciccione commented
ping @m2049r

2018-05-27 12:12 UTC, m2049r commented
next release will pick up all pending translations.

2018-07-27 08:46 UTC, merged