Swedish translation of strings.xml
m2049r/xmrwallet pull request #261
Opened 2018-04-26 10:59 UTC by ordtrogen

The other two files (about.xml and help.xml) will be provided by another contributor (@noooxi) so no need to wait for them to be added to this PR

2018-04-26 12:54 UTC, erciccione commented
Thanks a lot @ordtrogen! Please remove all strings labelled `translatable="false">`

2018-04-29 11:50 UTC, erciccione approved these changes

2018-04-30 19:49 UTC, m2049r requested changes
Missing:

- info_crazypass_enabled
- prompt_fingerprint_auth
- bad_fingerprint
- generate_fingerprint_hint
- generate_fingerprint_warn

2018-04-30 20:46 UTC, ordtrogen commented
Now, then ...

2018-05-06 08:01 UTC, erciccione approved these changes

2018-07-27 09:57 UTC, merged