New strings translated to French
m2049r/xmrwallet pull request #412
Opened 2018-09-20 15:30 UTC by el00ruobuob

Ready for review @erciccione

2018-09-20 16:40 UTC, erciccione requested changes
Thanks for this, just a small mistake to fix

2018-09-20 16:40 UTC, erciccione commented on app/src/main/res/values-fr/strings.xml
> +    <string name="send_address_no_dnssec">OpenAlias sans DNSSEC - l'adresse pourrait être usurpée !</string>
You forgot to escape `l'adresse` here

2018-09-20 16:46 UTC, el00ruobuob commented on app/src/main/res/values-fr/strings.xml
> +    <string name="send_address_no_dnssec">OpenAlias sans DNSSEC - l'adresse pourrait être usurpée !</string>
Damned. I fix this soon.

2018-09-21 05:11 UTC, el00ruobuob commented on app/src/main/res/values-fr/strings.xml
> +    <string name="send_address_no_dnssec">OpenAlias sans DNSSEC - l'adresse pourrait être usurpée !</string>
fixed.

2018-09-21 05:11 UTC, el00ruobuob commented
It should be good now.

2018-09-21 07:32 UTC, m2049r approved these changes

2018-09-21 11:30 UTC, erciccione approved these changes

2018-09-21 12:36 UTC, merged