Translation to Brazilian Portuguese (pt-rBR).
m2049r/xmrwallet pull request #455
Opened 2018-10-23 23:31 UTC by vp1111

2018-10-24 01:19 UTC, shigutso requested changes
Small things I would change, other than that it's a pretty solid translation to pt-BR!

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>Se você precisa de um novo endereço Monero</p>
<p>Se você precisa de um novo endereço Monero!</p>
> Missing the exclamation mark from the original text

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/help.xml
> +        aos teus fundos para <em>qualquer pessoa</em>!
aos teus fundos = a seus fundos

Maybe?

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>Suas chaves nunca saem do dispositivo da Ledger, então é preciso plugá-lo
plugá-lo = conectá-lo

Maybe?

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>Aqui ficam suas carteiras. Elas estão numa pasta chamada <tt>monerujo</tt> no armazenamento
"Elas estão em uma pasta"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/help.xml
> +      e decide por sua própria conta se este é um serviço que você quer usar. A equipe Monerujo não está associada com o XMR.TO
"e decida por sua própria conta"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/help.xml
> +        e decide por sua própria conta se este é um serviço que você quer usar. A equipe Monerujo não está associada com o XMR.TO
"e decida por sua própria conta"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="password_fair">É &#8230;</string>
"É..."

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +        <b>Você colocou um endereço de Bitcoin.</b><br/>
"um endereço Bitcoin"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +        <b>Voc6e pode enviar %1$s &#8212; %2$s BTC</b>.<br/>
"Você"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="service_progress">Finalizando o processo &#8230;\nPode demorar um pouquinho</string>
"um pouco"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="send_xmrto_timeout">Demorou demais, amigo!</string>
"Demorou demais!"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="message_camera_not_permitted">Sem câmera = Sem escaneio de códigos QR!</string>
"Sem câmera = Impossível escanear códigos QR!"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +        <p>Nós queremos relembrar que qualquer pessoa com acesso às suas digitais poderá espiar o seu saldo.</p>
"Queremos lembrar"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="generate_buttonGenerate">\'Bora criar essa carteira!</string>
"Vamos criar essa carteira logo!"

2018-10-24 01:19 UTC, shigutso commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="generate_wallet_dot">Não posso começar com .</string>
"Não pode começar"

2018-10-24 02:51 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="password_fair">É &#8230;</string>
&#8230; é o código HTML para [Horizontal Ellipsis](https://www.fileformat.info/info/unicode/char/2026/index.htm).

2018-10-24 02:51 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>Aqui ficam suas carteiras. Elas estão numa pasta chamada <tt>monerujo</tt> no armazenamento
Penso em deixar o "numa" pelo teor mais informal da carteira Monerujo (com pequenas piadinhas, etc).

2018-10-24 02:51 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        aos teus fundos para <em>qualquer pessoa</em>!
Tenho impressão que o artigo precisa combinar com o substantivo que nesse caso é masculino (os fundos), mas vou mudar para "aos seus fundos" para normalizar o tempo verbal.

2018-10-24 11:37 UTC, erciccione commented
Thanks for the review @shigutso. @netrik182 maybe you also want to review this

2018-10-24 15:01 UTC, netrik182 commented
Yes, I can review it tonight. Thanks

2018-10-25 03:07 UTC, netrik182 reviewed
Fiz minhas revisões e comentários. São poucos pontos. No geral, tudo ok.

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/about.xml
> +        no objetivo de efetuar as transações e transmiti-las à rede Monero de forma encriptada.
```suggestion
        no objetivo de efetuar as transações e transmití-las à rede Monero de forma encriptada.
```

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
> use uma longa frase

Aqui fiquei um pouco em dúvida se vai manter a mesma tradução da linha 8 ```uma palavra-passe longa``` ou o texto original tbm era diferente.

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
A mesma observação apontada na linha 27.

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
Aqui tbm.

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
Aqui tbm.

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>Selecione uma carteira para abri-la ou toque em \"+\" para criar uma nova.
```suggestion
        <p>Selecione uma carteira para abrí-la ou toque em \"+\" para criar uma nova.
```

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Monero para o endereço errado. </p>
```suggestion
        Monero para o endereço errado.</p>
```

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="send_sweepall">Enviar todo o fundo disponível nesta conta!</string>
Proponho que a palavra `fundo` seja alterada para `saldo`.

2018-10-25 03:07 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="nfc_tag_read_success">Sucesso de leitura da tag</string>
```suggestion
    <string name="nfc_tag_read_success">Sucesso na leitura da tag</string>
```

2018-10-25 12:23 UTC, bitlamas commented on app/src/main/res/values-pt-rBR/about.xml
> +        no objetivo de efetuar as transações e transmiti-las à rede Monero de forma encriptada.
Qual seria o motivo do acento agudo na última sílaba? Como a palavra não é uma oxítona terminada em `a`, `e` ou `o`, ela precisa ser ou um ditongo ou um hiato para receber o acento (e.g. distribuí-lo, mas não em traduzi-lo).

2018-10-25 12:26 UTC, bitlamas commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
Eu decidi não usar a tradução `palavra-passe`, apesar dela existir, porque é uma terminologia muito pouco usada no Brasil. As pessoas compreendem com mais facilidade uma `senha forte` do que `palavra-passe longa`. Esse caso não se aplica em Portugal onde eles usam `palavra-passe` e mesmo `frase-passe` eu já li. Acredito que se o objetivo é a popularização do Monerujo para o público em massa do Android, pode ser melhor usar termos mais populares. O que acha?

2018-10-25 12:40 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>Selecione uma carteira para abri-la ou toque em \"+\" para criar uma nova.
Mesmo caso que o "transmiti-la". Que eu saiba essa palavra **não** leva acento.

2018-10-25 13:35 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
Além do mais, utilizar `palavra-passe` iria sentido contrário ao de outras aplicações código aberto, como Linux, que utilizam majoritariamente `senha` para Português do Brasil e `palavra-passe` para Português de Portugal.

2018-10-25 13:42 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
Ah, acabo de ver que você está comentando da linha 8. Hmm.
Vou mudar para `A senha é utilizada para proteger as informações da carteira. Use uma senha forte.`
Acredito que fique claro o suficiente para o usuário que ele deve usar uma boa senha. Talvez senha "longa e forte", não sei. O que acha?

2018-10-25 16:42 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Use uma senha forte - ou melhor, use uma longa frase.</p>
Acredito que `uma senha longa e forte` representa bem o objetivo de se ter uma senha longa e forte hahaha

Por mim usaria isso em todas as passagens.

2018-10-26 14:29 UTC, shigutso commented on app/src/main/res/values-pt-rBR/about.xml
> +        no objetivo de efetuar as transações e transmiti-las à rede Monero de forma encriptada.
Sim, se não me engano somente verbos terminados em AR ER e OR levam acento nesses casos.

2018-10-26 14:36 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/about.xml
> +        no objetivo de efetuar as transações e transmiti-las à rede Monero de forma encriptada.
Como eu comentei, existem alguns casos onde acentua-se a forma verbal mesmo se terminados em IR, como distribuir. Encontrei uma [boa explicação](https://www.migalhas.com.br/Gramatigalhas/10,MI23516,81042-Punilo+ou+punilo+Concluilo+ou+concluilo) do professor José Maria da Costa.

Portanto no caso de transmitir e abrir elas não levam acento.

2018-10-27 17:36 UTC, vp1111 commented
@netrik182 let me know if you want to discuss any other suggestions for this PR.

2018-10-28 01:04 UTC, netrik182 commented
> @netrik182 let me know if you want to discuss any other suggestions for this PR.

No, that's it. Should be ready for production, I think.

2018-10-28 01:07 UTC, shigutso approved these changes

2018-10-28 01:11 UTC, netrik182 approved these changes

2018-10-28 16:47 UTC, erciccione approved these changes

2018-10-31 11:22 UTC, m2049r approved these changes

2018-10-31 11:24 UTC, merged