[i18n-IT] Aligned translation of new features
m2049r/xmrwallet pull request #461
Opened 2018-11-04 09:21 UTC by hrumag

Good morning.
@erciccione, @serhack, please review.

2018-11-04 09:01 UTC, serhack commented on app/src/main/res/values-it/help.xml
> +        <h2>Modalità strada</h2>
Funny.. :- ) "strada"

2018-11-04 09:01 UTC, serhack approved these changes

2018-11-04 13:00 UTC, erciccione reviewed
Could you keep the same formatting of the original strings? for consistency and readability (instead of one line for paragraph)

2018-11-04 15:12 UTC, hrumag commented
It's pretty difficult since I'm using vim and the formatting (CR) depends on the width of the window.
Let me know if there are problems.

2018-11-04 16:32 UTC, erciccione commented
Now looks like the build fails

2018-11-04 17:34 UTC, hrumag commented
All should work now.
I took the occasion to squash.

2018-11-04 22:18 UTC, m2049r requested changes

2018-11-04 22:18 UTC, m2049r commented on app/src/main/res/values-it/strings.xml
>      <string name="menu_info">Dettagli</string><!--Changed to: Show Secrets!-->
could please (re-)translate this: it was changed from "Details" to "Show Secrets!"

2018-11-05 17:25 UTC, m2049r approved these changes

2018-11-05 17:26 UTC, merged