updated pt-BR translation help and node strings
m2049r/xmrwallet pull request #491
Opened 2018-11-29 03:38 UTC by netrik182

2018-12-15 14:26 UTC, m2049r commented
@vp1111 do you have a new ETA for the review?

2018-12-16 01:15 UTC, vp1111 commented
My business trip got extended until this Tuesday. Wednesday I will be home so I should be able to properly do it before the next weekend if that's alright.

2018-12-22 17:49 UTC, bitlamas requested changes
Some of the reviews are not grammar mistakes, but suggestions on how to improve the translation from a "literal translation" to a more contextualized, adapted version.

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>O modo de rua pode ser ativado/desativado no menu ou no ícone da cabeça do Gunther. Neste modo, o seu
O modo ~~de~~ rua pode ser [...]

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        outro lugar público. Transações anteriores também serão ocultas. Novas transações serão mostradas, então
Manter o mesmo tempo de verbo no parágrafo. No começo é usado o presente (`o seu saldo não é mostrado`) e posteriormente é usado o futuro (`novas transações serão mostradas`).

Sugestão:
Mudar os verbos "mostrar" para "exibir", que é o mais comumente visto em outros softwares localizados em português. _E.g._ O seu saldo não é ~~mostrado~~ **exibido** em nenhuma tela [...]

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        você pode ver que você enviou/recebeu doces Moneroj!</p>
Apesar de eu entender o teor cômico do Monerujo ao usar `sweet Moneroj`, eu acho que a tradução soa estranha em português e não acredito que é de imediata compreensão a um novo usuário. A frase poderia ser melhor adaptada, evitando a repetição do pronome "você". _E.g._ `Novas transações são exibidas, o que permite verificar quando você receber/enviar Moneroj!`

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>A lista de nós mostra todos os nós conhecidos atualmente. Além disso, a data e hora
Sugestão:
Além disso, a data e hora do último bloco sincronizado por cada nó é exibido abaixo do seu nome.

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        é mostrado ao lado de cada nó.</p>
Ocultar o substantivo quando der para evitar sua repetição. Por exemplo, o parágrafo:

> Além disso, a data e hora do último bloco conhecido para cada **nó** é mostrado sob o nome do **nó**. Um ícone representando o comportamento de resposta do **nó** (o que indica o nível de conectividade esperado) é mostrado ao lado de cada **nó**.

Uma sugestão para este parágrafo seria:

> Além disso, a data e hora do último bloco sincronizado por cada **nó** é exibido abaixo do seu nome. Um ícone representando o comportamento de resposta do **nó** (que indica o nível de conectividade esperado) é exibido ao lado.

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        <p>O Monerujo escolherá o nó ideal dentre os marcados sempre que você usá-lo.
Sugestão: O Monerujo _sempre_ escolherá o nó ideal dentre os marcados ~~sempre que você usá-lo~~.

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Ele faz isso verificando a altura do bloco (quão atualizado
Acho que podemos manter o padrão de definir os nós como "sincronizados" ao invés de atualizados (como é usado no GUI). Sugestão: [...] (quão sincronizado está o nó?) [...]

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        escolheria agora. A parte inferior da lista mostraria nós muito lentos ou indisponíveis.</p>
[...] escolheria **agora** → escolheria **nesse momento** (ou) **nesse caso**.
Faço esta sugestão pois imagino que há uma tela de exemplo dando suporte ao parágrafo.

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        insirir os detalhes do nó no diálogo seguinte.
insirir → inserir

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        entrada obrigatória.
Sugestão: entrada → informação

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Ou a combinação Nome do Host/Porta não aponta para um Nó Monero verdadeiro!
Sugestão: [...] para um Nó Monero ~~verdadeiro~~ **válido**.

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        Depois que o teste passar (sem erro), você estará apto a pressionar &quot;OK&quot; para salvar &amp;
Sugestão: [...] você ~~estará apto a~~ **poderá** pressionar

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        escanear a rede para nós remotos na porta 18089. Ele começa perguntando ao seus
escanear a rede ~~para~~ **por** nós remotos [...]

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        perguntando por seus colegas, e assim por diante. Se você não tem nós marcados como favoritos
por seus ~~colegas~~ **pares**, e assim por diante

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/help.xml
> +        escaneamento para quando 10 nós remotos são encontrados no total.</p>
o escaneamento ~~para~~ **termina** quando 10 nós remotos [...]

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="node_height">Último bloco atualizado em: %1$s</string>
Último bloco ~~atualizado~~ sincronizado em

2018-12-22 17:49 UTC, vp1111 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="node_refresh_wait">Por favor, aguardo o escaneamento terminar</string>
Por favor, aguard~~o~~**e** o escaneamento [...]

2018-12-30 12:33 UTC, netrik182 commented
thanks @vp1111 for the review. Files were updated.

2018-12-30 16:17 UTC, erciccione approved these changes

2018-12-31 13:18 UTC, bitlamas approved these changes

2019-01-05 12:42 UTC, merged