translated 'help', 'strings' and 'about' to esperanto
m2049r/xmrwallet pull request #531
Opened 2019-02-09 15:32 UTC by Keksoj

Created app/src/main/res/values-eo/ directory and all three translated files

2019-02-09 16:19 UTC, erciccione requested changes
Looks like there is at least a duplicated string ("send_address_hint"). You were talking about 10 strings that you added because missing. Please make sure they were actually missing, probably only their value changed.

2019-02-09 17:14 UTC, Keksoj commented
The duplicated string mistake and the 10 extra strings come from the https://github.com/m2049r/xmrwallet/commit/39d048fd5e4f177daee298aad16c67187dd6a98b commit, to which I had not updated. 
Fixed it.

2019-02-09 22:28 UTC, m2049r commented on app/src/main/res/values-eo/about.xml
> +        <p>Ni eble ĝisdatigos tiun privatecan politikon de temp' al tempo. Ni
apostrophes need to be escaped - either as \' or as &apos;

2019-02-09 22:28 UTC, m2049r requested changes
please fix the apostrophe issue

2019-02-09 22:46 UTC, Keksoj commented
done

2019-02-10 22:25 UTC, erciccione approved these changes
Looks good to me. Thanks @Keksoj

2019-02-11 06:41 UTC, m2049r approved these changes
Thanks!

2019-02-11 06:41 UTC, merged