Update strings.xml
m2049r/xmrwallet pull request #575
Opened 2019-04-22 09:33 UTC by jindouyunz

updated on 4/22/2019 version 2, Jindouyunz.

2019-04-22 09:53 UTC, erciccione commented
Pinging past translators for review: @uiharu-s @bitOMG

2019-05-01 12:33 UTC, erciccione commented
Reping translators (Only the last 20-25 strings need to be reviewed)

2019-05-04 12:04 UTC, erciccione commented
Maybe @xmrnoblesse?

2019-05-05 17:36 UTC, m2049r commented
i will wait for review?

2019-05-06 10:21 UTC, erciccione commented
@m2049r I'm out of people to ping, if you want to push this, fine for me.

2019-05-06 12:40 UTC, Lafudoci commented
I'll review it now. Though I'm not simplified zh native speaker, but I could read most of them.

2019-05-06 13:04 UTC, Lafudoci requested changes
Some translations should be revised.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="connect_testnet" translatable="false">测试网（供开发用户使用的门罗测试网）</string>
Strings with attrib translatable="false" shouldn't be translated.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="send_xmrto_timeout">您已经等待足够长的时间了！</string>
Please check if this translation is accurate. Timeout means "too" long. But the translation seems to mean "enough".

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="bad_fingerprint">无法是被您的指纹，请重试。</string>
"是被" should be a typo of "识别".

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="generate_buttonGenerate">Make me a wallet already!</string>
This string wasn't translated. From previous version it could be "建立钱包！".

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="generate_wallet_type_ledger" translatable="false">Ledger</string>
Strings with attrib translatable="false" shouldn't be translated.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="send_qr_hint" translatable="false">扫描</string>
Strings with attrib translatable="false" shouldn't be translated.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +</string-array>
@m2049r Does this array should be here?

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="toast_ledger_detached">%1$s 已从附加中删除</string>
Please check if these translation are accurate. The "attach" and "detach" means connect or disconnect to ledger device.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="progress_nfc_write">标签写入中</string>
Does "标签" enough to present "NFC label" well? "NFC标签" might be more precise.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="tx_account_formatted" translatable="false">(%1$d, %2$d)</string>
Strings with attrib translatable="false" shouldn't be translated.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="unknown_amount" translatable="false">\?\?\?</string>
Strings with attrib translatable="false" shouldn't be translated.

2019-05-06 13:04 UTC, Lafudoci commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="street_sweep_amount">所有东西！</string>
Please check if these translation are accurate. This string means all the money in this account.

2019-05-07 09:03 UTC, jindouyunz commented on app/src/main/res/values-zh-rCN/strings.xml
> +<string name="bad_fingerprint">无法是被您的指纹，请重试。</string>
Much thanks Lafudoci，I'll revise those translations.

2019-05-12 01:29 UTC, Lafudoci commented
@m2049r @erciccione , IIRC, the strings with attrib translatable="false" could be removed from xml file, right? And the currency item array I don't know if it should be there.

2019-05-12 11:28 UTC, erciccione commented
Afaik, yes, they can be removed. 

That array is labelled `translatable= 'false'`, so i guess it could be removed, but i would wait @m2049r 's confirmation on that.

2019-05-12 20:59 UTC, m2049r commented
yes, `translatable=false` should be left out entirely - leaving them in creates errors on build.

2019-05-13 05:26 UTC, Lafudoci commented
@jindouyunz , sorry I should ask earlier. As you can see above comments, please remove all the string (entire line) with `translatable=false`, including the currency array. Then is PR should be good to go!

2019-05-13 07:07 UTC, jindouyunz commented
> 
> 
> @jindouyunz , sorry I should ask earlier. As you can see above comments, please remove all the string (entire line) with `translatable=false`, including the currency array. Then is PR should be good to go!

Sure，I'll do it now.

2019-05-13 07:25 UTC, Lafudoci approved these changes
Translation reviewed.

2019-05-13 13:13 UTC, erciccione approved these changes
Looks good. Thanks to both :)

2019-05-18 06:40 UTC, m2049r approved these changes

2019-05-18 06:40 UTC, merged