Update PT-rBR strings
m2049r/xmrwallet pull request #813
Opened 2022-02-08 00:49 UTC by jontaix

2022-02-09 07:02 UTC, netrik182 requested changes
Thanks for your translation @jontaix 

I made simple suggestions to improve it and keep consistency across multiple Monero Wallets. Please let me know what you think.

2022-02-09 07:02 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="node_waiting">\u00A0ESPERANDO POR NODE\u00A0</string>
```suggestion
    <string name="node_waiting">\u00A0ESPERANDO PELO NÓ\u00A0</string>
```

I would suggest using the word "nó" instead of "node" to keep consistency. For example:
- https://github.com/m2049r/xmrwallet/blob/7b96baeca7f216c943ad5d376e6838f9679e74b0/app/src/main/res/values-pt-rBR/about.xml#L43
- https://github.com/m2049r/xmrwallet/blob/7b96baeca7f216c943ad5d376e6838f9679e74b0/app/src/main/res/values-pt-rBR/strings.xml#L99

And many other occurrences.

2022-02-09 07:02 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="tor_enable_background">"Permitir Início em Segundo-plano" nas Opções do Orbot para usar o Tor!</string>
```suggestion
    <string name="tor_enable_background">"Permitir inicializações em segundo plano" nas opções do Orbot para usar o Tor!</string>
```

My suggestion here and bellow is to refrain from using capital letters for each word. This is common in English but not in Portuguese (see [these tips](https://github.com/monero-ecosystem/monero-translations/blob/master/translation-tips.md#6-english-is-weird)).

Also changed to "Permitir inicializações em segundo plano" to match the real app. If you install Orbot and change the language to Portuguese, that's how it's written there.

2022-02-09 07:02 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="seed_offset_hint">Frase de "Seed Offset" (opcional)</string>
As stated above, my suggestion is to refrain from using capital letters for each word. This is common in English but not in Portuguese (see [these tips](https://github.com/monero-ecosystem/monero-translations/blob/master/translation-tips.md#6-english-is-weird)).

2022-02-09 07:02 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="seed_offset_hint">Frase de "Seed Offset" (opcional)</string>
In Monero GUI this string was translated differently. Maybe we can consider keeping it consistent as well.

> Senha de dedução da semente (opcional)

https://github.com/monero-project/monero-gui/blob/e9afaa9cc89acc06b41e05748c5795efdeee9627/translations/monero-core_pt-br.ts#L3722

2022-02-10 14:14 UTC, jontaix commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="node_waiting">\u00A0ESPERANDO POR NODE\u00A0</string>
Thanks for the suggestions. I was confused whether I should translate certain words or not. I agree with your corrections to maintain consistency.

2022-02-10 14:21 UTC, jont4 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="seed_offset_hint">Frase de "Seed Offset" (opcional)</string>
I didn't find a translation that satisfied me for "Seed Offset" so I kept it as a technical expression.

2022-02-12 11:57 UTC, netrik182 commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="seed_offset_hint">Frase de "Seed Offset" (opcional)</string>
Would you like to keep these terms in English? As I mentioned, in the official Monero GUI Wallet it's translated as 'Senha de dedução da semente".

Please let me know so I can approve this PR.

2022-02-21 22:37 UTC, jontaix commented on app/src/main/res/values-pt-rBR/strings.xml
> +    <string name="seed_offset_hint">Frase de "Seed Offset" (opcional)</string>
sorry for delay to answer. 
I think is better your version in Portuguese as in the monero GUI.

2022-02-23 15:31 UTC, netrik182 approved these changes
Looks good! Thanks @jontaix

2022-02-23 15:31 UTC, netrik182 commented
ping @m2049r

2022-05-01 09:51 UTC, merged